// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dep02 from "@testrepo/dep02/src/Dep02.mjs";

function log(param) {
  console.log("02");
  Dep02.log(undefined);
}

export {
  log ,
}
/* No side effect */
