// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dep01 from "@testrepo_yarn/dep01/src/Dep01.mjs";

console.log("01");

Dep01.log();

var $$Array;

var $$String;

export {
  $$Array ,
  $$String ,
}
/*  Not a pure module */
