// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "./Array.mjs";

function log(param) {
  $$Array.forEach([
        "a",
        "b"
      ], (function (prim) {
          console.log(prim);
        }));
}

export {
  log ,
}
/* No side effect */
