// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "./Array.js";
import * as NS_alias$$atNewNamespace from "@testrepo/new-namespace/src/NS_alias.js";

function log() {
  $$Array.forEach([
        "a",
        "b"
      ], (function (prim) {
          console.log(prim);
        }));
}

console.log(NS_alias$$atNewNamespace.hello_world());

export {
  log ,
}
/*  Not a pure module */
