// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Array$TestrepoDep02 from "./Array.mjs";

function log(param) {
  Array$TestrepoDep02.forEach([
        "a",
        "b"
      ], (function (prim) {
          console.log(prim);
        }));
}

export {
  log ,
}
/* No side effect */
