// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Other_module$$atNewNamespace from "./Other_module.mjs";

function hello_world(param) {
  return "Hello world";
}

Other_module$$atNewNamespace.bla(undefined);

export {
  hello_world ,
}
/*  Not a pure module */
