// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dep01 from "@testrepo/dep01/src/Dep01.mjs";
import * as Dep02$TestrepoMain from "./Dep02.mjs";

console.log("01");

Dep01.log(undefined);

Dep02$TestrepoMain.log(undefined);

var $$Array;

var $$String;

export {
  $$Array ,
  $$String ,
}
/*  Not a pure module */
